import { LLMModel } from './llm_interface.js';
import { type RitualContext, type RitualPlan } from "./types.js";
import { handleTraverse, handleEnact, handleDivine, handleLull, handleDiscourse, handleQuery, handleResponse, handlePreExecutionCheck, handleUserConfirmation, handleCodeGeneration, handleUserInput, handleStepProposal, handleAssistedEditing, handleDreamNavigation, handleReflectionNavigation, handleAddReflection } from "./ritual_step_handlers.js";
export declare function getInitialContext(): RitualContext;
export declare function safeQuery(prompt: string, label: string, model?: LLMModel): Promise<string>;
export declare function generateRitual(input: string, context: RitualContext, model?: LLMModel, analysisResult?: string, startingIndex?: number): Promise<RitualPlan | null>;
declare const defaultIncantationHandlers: {
    handleTraverse: typeof handleTraverse;
    handleEnact: typeof handleEnact;
    handleDivine: typeof handleDivine;
    handleLull: typeof handleLull;
    handleDiscourse: typeof handleDiscourse;
    handleQuery: typeof handleQuery;
    handleResponse: typeof handleResponse;
    handlePreExecutionCheck: typeof handlePreExecutionCheck;
    handleUserConfirmation: typeof handleUserConfirmation;
    handleCodeGeneration: typeof handleCodeGeneration;
    handleUserInput: typeof handleUserInput;
    handleStepProposal: typeof handleStepProposal;
    handleAssistedEditing: typeof handleAssistedEditing;
    handleDreamNavigation: typeof handleDreamNavigation;
    handleReflectionNavigation: typeof handleReflectionNavigation;
    handleAddReflection: typeof handleAddReflection;
};
export declare function executeRitualPlan(plan: RitualPlan, context: RitualContext, ask: (q: string) => Promise<string>, dependencies?: {
    generateRitual: typeof generateRitual;
    stepHandlers: typeof defaultIncantationHandlers;
}): Promise<any[]>;
export declare function generateSelfObservation(context: RitualContext): Promise<string>;
export {};
